var myString;
var myVar;
var strArr;
var numArr;
var strNumTuple;
var tupleArray;
myString = "Hello World  Jia and Naina";
myVar = true;
strArr = ['Hello', 'World'];
numArr = [4.5, 0.4];
strNumTuple = ['Anu', 37];
tupleArray = [['Jia', 4.5], ['Naina', 0.4]];
var myVoid = undefined;
var myUndefined = undefined;
var myNull = null;
console.log(myVar);
console.log(myString);
console.log(strArr);
console.log(numArr);
console.log(strNumTuple);
console.log(tupleArray);
console.log(myVoid);
console.log(myUndefined);
console.log(myNull);
