@root = https://localhost:7293

# Create a User - Valid Input

POST {{root}}/demo/CreateUser
Content-Type: application/json

{
  "userName" : "Sample",
  "displayName" : "Sample"
}

###

# Create a User - Invalid User

POST {{root}}/demo/CreateUser
Content-Type: application/json

{
  "userName": "",
  "displayName" : ""
}
