//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF002_WebClient.HelloService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parent", Namespace="http://schemas.datacontract.org/2004/07/DataService")]
    [System.SerializableAttribute()]
    public partial class Parent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Father {
            get {
                return this.FatherField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherField, value) != true)) {
                    this.FatherField = value;
                    this.RaisePropertyChanged("Father");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mother {
            get {
                return this.MotherField;
            }
            set {
                if ((object.ReferenceEquals(this.MotherField, value) != true)) {
                    this.MotherField = value;
                    this.RaisePropertyChanged("Mother");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloService.ILearningService")]
    public interface ILearningService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearningService/GetUserName", ReplyAction="http://tempuri.org/ILearningService/GetUserNameResponse")]
        string GetUserName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearningService/GetUserName", ReplyAction="http://tempuri.org/ILearningService/GetUserNameResponse")]
        System.Threading.Tasks.Task<string> GetUserNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearningService/GetParents", ReplyAction="http://tempuri.org/ILearningService/GetParentsResponse")]
        WCF002_WebClient.HelloService.Parent GetParents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearningService/GetParents", ReplyAction="http://tempuri.org/ILearningService/GetParentsResponse")]
        System.Threading.Tasks.Task<WCF002_WebClient.HelloService.Parent> GetParentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILearningServiceChannel : WCF002_WebClient.HelloService.ILearningService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LearningServiceClient : System.ServiceModel.ClientBase<WCF002_WebClient.HelloService.ILearningService>, WCF002_WebClient.HelloService.ILearningService {
        
        public LearningServiceClient() {
        }
        
        public LearningServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LearningServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LearningServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LearningServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUserName() {
            return base.Channel.GetUserName();
        }
        
        public System.Threading.Tasks.Task<string> GetUserNameAsync() {
            return base.Channel.GetUserNameAsync();
        }
        
        public WCF002_WebClient.HelloService.Parent GetParents() {
            return base.Channel.GetParents();
        }
        
        public System.Threading.Tasks.Task<WCF002_WebClient.HelloService.Parent> GetParentsAsync() {
            return base.Channel.GetParentsAsync();
        }
    }
}
