var myString;
var myNumber;
var myBoolean;
var myArray;
var strNumTuple;
var arrayOfTuple;
myString = "Hello World";
myNumber = 1;
myBoolean = true;
myArray = ['Sample', 'Array'];
strNumTuple = ['John Doe', 51];
arrayOfTuple = [['John Doe', 52], ['Jane Doe', 50]];
console.log(myString);
console.log(myNumber);
console.log(myBoolean);
console.log(myArray);
console.log(strNumTuple);
console.log(arrayOfTuple);
